import Head from "next/head";
import LayoutMain from "@/layouts/Main";
import cn from "classnames";
export default function Home() {
    return (
        <>
            <Head>
                <title>Giant React App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LayoutMain>
                <div className={cn("upper-page")} id="home">
                    <div className={cn("hero-fullscreen")}>
                        <div className={cn("top-shadow light")}></div>

                        <div className={cn("hero-fullscreen-FIX")}>
                            <div
                                className={cn("hero-bg bg-img-SINGLE-LIGHT")}
                            ></div>
                        </div>
                    </div>

                    <div className={cn("center-container")}>
                        <div className={cn("center-block fadeIn-element")}>
                            <h1 className={cn("home-page-title dark")}>
                                Giant<span className={cn("registered")}>®</span>
                            </h1>
                            <div className={cn("home-page-subtitle-carousel")}>
                                <h2 className={cn("home-page-title dark")}>
                                    Simplicity is complex
                                </h2>
                            </div>
                        </div>
                    </div>
                </div>
            </LayoutMain>
        </>
    );
}
